"""books: внутренние книги компании

Схема раздела «Книги»: таблицы, импортированные из Google, живут здесь как
типизированные строки, а не как снимок ячеек. Из неё же дашборд берёт цифры.

Что заложено сразу, чтобы не переделывать потом
───────────────────────────────────────────────
**`workspace_id` в каждой таблице правды.** Пространство пока одно, но
дописывать многоарендность позже — значит переписать каждый запрос и каждую
ревизию. Колонка сейчас стоит ничего.

**Составные внешние ключи `(x_id, workspace_id)`.** Одной колонки
`workspace_id` мало: ничто не помешало бы строке одного пространства сослаться
на таблицу другого, и утечка между арендаторами выглядела бы как обычная
строка. Составная ссылка делает несоответствие невозможным на уровне схемы, а
не на уровне внимательности того, кто пишет запрос.

**Деньги — `numeric(18,2)`.** Сумма тысячи строк по копейкам на двоичной
плавающей точке не сходится, и расхождение всплывает не там, где возникло, а в
контрольной сумме на экране начальника.

**`jsonb` только там, где форма действительно неизвестна** — `rows.values` и
`rows.base`. Привязки, каталог ролей, настройки — колонки. jsonb «на всякий
случай» и есть будущий мусор.

**Текст с `CHECK` вместо `ENUM`.** Тип-перечисление в Postgres больно менять:
добавление значения требует `ALTER TYPE` и не откатывается внутри транзакции.

**Единая схема имён** (`ix_`/`uq_`/`ck_`/`fk_`/`pk_` из `books/db.py`). У
соседних модулей её не было, и цена уже известна: ревизия 0009 выравнивала 24
индекса, разошедшихся с моделями настолько, что автогенерация предлагала
пересоздавать их на каждом прогоне.

`row_facts` — единственная производная таблица здесь. Её можно уронить и
собрать заново из `rows` × `bindings`; всё остальное — правда.

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-04 05:11:26.163305

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA = "books"


def upgrade() -> None:
    bind = op.get_bind()
    # У SQLite схем нет — там модуль собирается через create_all из тех же
    # моделей (app/books/db.py), и ревизия ему не нужна.
    if bind.dialect.name == "sqlite":
        return

    # Автогенерация создание схемы не выдаёт: она видит только таблицы.
    op.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_catalog',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint("value_type IN ('text', 'number', 'money', 'date', 'bool', 'enum', 'formula', 'unknown')", name=op.f('ck_role_catalog_value_type')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_role_catalog')),
    schema='books'
    )
    op.create_table('row_edits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("source IN ('app', 'grid', 'import')", name=op.f('ck_row_edits_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_row_edits')),
    schema='books'
    )
    op.create_index('ix_row_edits_row_at', 'row_edits', ['row_id', 'at'], unique=False, schema='books')
    op.create_index('ix_row_edits_table_at', 'row_edits', ['table_id', 'at'], unique=False, schema='books')
    op.create_index('ix_row_edits_workspace_id', 'row_edits', ['workspace_id'], unique=False, schema='books')
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug')),
    schema='books'
    )
    op.create_table('books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source_kind IN ('google_sheets', 'app')", name=op.f('ck_books_source_kind')),
    sa.ForeignKeyConstraint(['workspace_id'], ['books.workspaces.id'], name=op.f('fk_books_workspace_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_books_id_workspace'),
    schema='books'
    )
    op.create_index('ix_books_workspace_id', 'books', ['workspace_id'], unique=False, schema='books')
    op.create_table('role_synonyms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_key', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('seed', 'learned')", name=op.f('ck_role_synonyms_source')),
    sa.ForeignKeyConstraint(['role_key'], ['books.role_catalog.key'], name=op.f('fk_role_synonyms_role_key'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['books.workspaces.id'], name=op.f('fk_role_synonyms_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_synonyms')),
    sa.UniqueConstraint('role_key', 'workspace_id', 'normalized', name='uq_role_synonyms_key'),
    schema='books'
    )
    op.create_index('ix_role_synonyms_normalized', 'role_synonyms', ['normalized'], unique=False, schema='books')
    op.create_table('import_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by', sa.Text(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('preview', 'applied', 'blocked', 'failed')", name=op.f('ck_import_runs_status')),
    sa.ForeignKeyConstraint(['book_id', 'workspace_id'], ['books.books.id', 'books.books.workspace_id'], name=op.f('fk_import_runs_book_id_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_runs')),
    schema='books'
    )
    op.create_index('ix_import_runs_book_started', 'import_runs', ['book_id', 'started_at'], unique=False, schema='books')
    op.create_index('ix_import_runs_workspace_id', 'import_runs', ['workspace_id'], unique=False, schema='books')
    op.create_table('tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('identity_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id', 'workspace_id'], ['books.books.id', 'books.books.workspace_id'], name=op.f('fk_tables_book_id_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables')),
    sa.UniqueConstraint('book_id', 'name', name='uq_tables_book_name'),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_tables_id_workspace'),
    schema='books'
    )
    op.create_index('ix_tables_workspace_id', 'tables', ['workspace_id'], unique=False, schema='books')
    op.create_table('fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('names', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('display', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('text', 'number', 'money', 'date', 'bool', 'enum', 'formula', 'unknown')", name=op.f('ck_fields_type')),
    sa.ForeignKeyConstraint(['table_id', 'workspace_id'], ['books.tables.id', 'books.tables.workspace_id'], name=op.f('fk_fields_table_id_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_fields_id_workspace'),
    sa.UniqueConstraint('table_id', 'key', name='uq_fields_table_key'),
    schema='books'
    )
    op.create_index('ix_fields_workspace_id', 'fields', ['workspace_id'], unique=False, schema='books')
    op.create_table('import_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=True),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['books.import_runs.id'], name=op.f('fk_import_issues_import_run_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_issues')),
    schema='books'
    )
    op.create_index('ix_import_issues_run', 'import_issues', ['import_run_id'], unique=False, schema='books')
    op.create_table('rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('base', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("origin IN ('source', 'app')", name=op.f('ck_rows_origin')),
    sa.CheckConstraint("state IN ('live', 'missing_in_source')", name=op.f('ck_rows_state')),
    sa.ForeignKeyConstraint(['table_id', 'workspace_id'], ['books.tables.id', 'books.tables.workspace_id'], name=op.f('fk_rows_table_id_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rows')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_rows_id_workspace'),
    schema='books'
    )
    op.create_index('ix_rows_table_position', 'rows', ['table_id', 'position'], unique=False, schema='books')
    op.create_index('ix_rows_table_source_key', 'rows', ['table_id', 'source_key'], unique=False, schema='books')
    op.create_index('ix_rows_workspace_id', 'rows', ['workspace_id'], unique=False, schema='books')
    op.create_table('bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('role_key', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('exact', 'squashed', 'loose', 'data', 'manual')", name=op.f('ck_bindings_confidence')),
    sa.ForeignKeyConstraint(['field_id', 'workspace_id'], ['books.fields.id', 'books.fields.workspace_id'], name=op.f('fk_bindings_field_id_workspace_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_key'], ['books.role_catalog.key'], name=op.f('fk_bindings_role_key'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id', 'workspace_id'], ['books.tables.id', 'books.tables.workspace_id'], name=op.f('fk_bindings_table_id_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bindings')),
    sa.UniqueConstraint('table_id', 'field_id', name='uq_bindings_table_field'),
    sa.UniqueConstraint('table_id', 'role_key', name='uq_bindings_table_role'),
    schema='books'
    )
    op.create_index('ix_bindings_workspace_id', 'bindings', ['workspace_id'], unique=False, schema='books')
    op.create_table('row_facts',
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('role_key', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('num_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('bool_value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_key'], ['books.role_catalog.key'], name=op.f('fk_row_facts_role_key'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id', 'workspace_id'], ['books.rows.id', 'books.rows.workspace_id'], name=op.f('fk_row_facts_row_id_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', 'role_key', name=op.f('pk_row_facts')),
    schema='books'
    )
    op.create_index('ix_row_facts_table_role', 'row_facts', ['table_id', 'role_key'], unique=False, schema='books')
    op.create_index('ix_row_facts_table_role_date', 'row_facts', ['table_id', 'role_key', 'date_value'], unique=False, schema='books')
    op.create_index('ix_row_facts_workspace_id', 'row_facts', ['workspace_id'], unique=False, schema='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_row_facts_workspace_id', table_name='row_facts', schema='books')
    op.drop_index('ix_row_facts_table_role_date', table_name='row_facts', schema='books')
    op.drop_index('ix_row_facts_table_role', table_name='row_facts', schema='books')
    op.drop_table('row_facts', schema='books')
    op.drop_index('ix_bindings_workspace_id', table_name='bindings', schema='books')
    op.drop_table('bindings', schema='books')
    op.drop_index('ix_rows_workspace_id', table_name='rows', schema='books')
    op.drop_index('ix_rows_table_source_key', table_name='rows', schema='books')
    op.drop_index('ix_rows_table_position', table_name='rows', schema='books')
    op.drop_table('rows', schema='books')
    op.drop_index('ix_import_issues_run', table_name='import_issues', schema='books')
    op.drop_table('import_issues', schema='books')
    op.drop_index('ix_fields_workspace_id', table_name='fields', schema='books')
    op.drop_table('fields', schema='books')
    op.drop_index('ix_tables_workspace_id', table_name='tables', schema='books')
    op.drop_table('tables', schema='books')
    op.drop_index('ix_import_runs_workspace_id', table_name='import_runs', schema='books')
    op.drop_index('ix_import_runs_book_started', table_name='import_runs', schema='books')
    op.drop_table('import_runs', schema='books')
    op.drop_index('ix_role_synonyms_normalized', table_name='role_synonyms', schema='books')
    op.drop_table('role_synonyms', schema='books')
    op.drop_index('ix_books_workspace_id', table_name='books', schema='books')
    op.drop_table('books', schema='books')
    op.drop_table('workspaces', schema='books')
    op.drop_index('ix_row_edits_workspace_id', table_name='row_edits', schema='books')
    op.drop_index('ix_row_edits_table_at', table_name='row_edits', schema='books')
    op.drop_index('ix_row_edits_row_at', table_name='row_edits', schema='books')
    op.drop_table('row_edits', schema='books')
    op.drop_table('role_catalog', schema='books')
    # Схема пустеет вместе с последней таблицей — убираем и её. Модуль обязан
    # сниматься начисто: «DROP SCHEMA books CASCADE» и каталога как не бывало.
    op.execute(f'DROP SCHEMA IF EXISTS "{SCHEMA}"')
    # ### end Alembic commands ###
